[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[env]
GROQ_API_KEY = "${{GROQ_API_KEY}}"
GROQ_MODEL = "llama3-70b-8192"
ENVIRONMENT = "production"
DEBUG = "false"